datasources:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: quality-go
  nats:
    host: localhost
    port: 4222
  mongo:
    host: localhost
    port: 27017
server:
  host: localhost
  port: 8080