// Code generated by MockGen. DO NOT EDIT.
// Source: roleHandler.go

// Package mock is a generated GoMock package.
package mock

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRoleHandler is a mock of RoleHandler interface
type MockRoleHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRoleHandlerMockRecorder
}

// MockRoleHandlerMockRecorder is the mock recorder for MockRoleHandler
type MockRoleHandlerMockRecorder struct {
	mock *MockRoleHandler
}

// NewMockRoleHandler creates a new mock instance
func NewMockRoleHandler(ctrl *gomock.Controller) *MockRoleHandler {
	mock := &MockRoleHandler{ctrl: ctrl}
	mock.recorder = &MockRoleHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRoleHandler) EXPECT() *MockRoleHandlerMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockRoleHandler) Save(c *gin.Context) {
	m.ctrl.Call(m, "Save", c)
}

// Save indicates an expected call of Save
func (mr *MockRoleHandlerMockRecorder) Save(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoleHandler)(nil).Save), c)
}

// Update mocks base method
func (m *MockRoleHandler) Update(c *gin.Context) {
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update
func (mr *MockRoleHandlerMockRecorder) Update(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleHandler)(nil).Update), c)
}

// Paginate mocks base method
func (m *MockRoleHandler) Paginate(c *gin.Context) {
	m.ctrl.Call(m, "Paginate", c)
}

// Paginate indicates an expected call of Paginate
func (mr *MockRoleHandlerMockRecorder) Paginate(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockRoleHandler)(nil).Paginate), c)
}

// Delete mocks base method
func (m *MockRoleHandler) Delete(c *gin.Context) {
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete
func (mr *MockRoleHandlerMockRecorder) Delete(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleHandler)(nil).Delete), c)
}
