// Code generated by MockGen. DO NOT EDIT.
// Source: departmentService.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	model "github.com/rojoherrero/quality-accounts/server/model"
	reflect "reflect"
)

// MockDepartmentService is a mock of DepartmentService interface
type MockDepartmentService struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentServiceMockRecorder
}

// MockDepartmentServiceMockRecorder is the mock recorder for MockDepartmentService
type MockDepartmentServiceMockRecorder struct {
	mock *MockDepartmentService
}

// NewMockDepartmentService creates a new mock instance
func NewMockDepartmentService(ctrl *gomock.Controller) *MockDepartmentService {
	mock := &MockDepartmentService{ctrl: ctrl}
	mock.recorder = &MockDepartmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDepartmentService) EXPECT() *MockDepartmentServiceMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockDepartmentService) Save(ctx context.Context, department []model.Department) error {
	ret := m.ctrl.Call(m, "Save", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockDepartmentServiceMockRecorder) Save(ctx, department interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDepartmentService)(nil).Save), ctx, department)
}

// Update mocks base method
func (m *MockDepartmentService) Update(ctx context.Context, department model.Department) error {
	ret := m.ctrl.Call(m, "Update", ctx, department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockDepartmentServiceMockRecorder) Update(ctx, department interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentService)(nil).Update), ctx, department)
}

// Paginate mocks base method
func (m *MockDepartmentService) Paginate(ctx context.Context, start, end int) ([]model.Department, error) {
	ret := m.ctrl.Call(m, "Paginate", ctx, start, end)
	ret0, _ := ret[0].([]model.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paginate indicates an expected call of Paginate
func (mr *MockDepartmentServiceMockRecorder) Paginate(ctx, start, end interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockDepartmentService)(nil).Paginate), ctx, start, end)
}

// Delete mocks base method
func (m *MockDepartmentService) Delete(ctx context.Context, code string) error {
	ret := m.ctrl.Call(m, "Delete", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDepartmentServiceMockRecorder) Delete(ctx, code interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentService)(nil).Delete), ctx, code)
}
