// Code generated by MockGen. DO NOT EDIT.
// Source: departmentHandler.go

// Package mock is a generated GoMock package.
package mock

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDepartmentHandler is a mock of DepartmentHandler interface
type MockDepartmentHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentHandlerMockRecorder
}

// MockDepartmentHandlerMockRecorder is the mock recorder for MockDepartmentHandler
type MockDepartmentHandlerMockRecorder struct {
	mock *MockDepartmentHandler
}

// NewMockDepartmentHandler creates a new mock instance
func NewMockDepartmentHandler(ctrl *gomock.Controller) *MockDepartmentHandler {
	mock := &MockDepartmentHandler{ctrl: ctrl}
	mock.recorder = &MockDepartmentHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDepartmentHandler) EXPECT() *MockDepartmentHandlerMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockDepartmentHandler) Save(c *gin.Context) {
	m.ctrl.Call(m, "Save", c)
}

// Save indicates an expected call of Save
func (mr *MockDepartmentHandlerMockRecorder) Save(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDepartmentHandler)(nil).Save), c)
}

// Update mocks base method
func (m *MockDepartmentHandler) Update(c *gin.Context) {
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update
func (mr *MockDepartmentHandlerMockRecorder) Update(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentHandler)(nil).Update), c)
}

// Paginate mocks base method
func (m *MockDepartmentHandler) Paginate(c *gin.Context) {
	m.ctrl.Call(m, "Paginate", c)
}

// Paginate indicates an expected call of Paginate
func (mr *MockDepartmentHandlerMockRecorder) Paginate(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockDepartmentHandler)(nil).Paginate), c)
}

// Delete mocks base method
func (m *MockDepartmentHandler) Delete(c *gin.Context) {
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete
func (mr *MockDepartmentHandlerMockRecorder) Delete(c interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartmentHandler)(nil).Delete), c)
}
