// Code generated by MockGen. DO NOT EDIT.
// Source: roleHandler.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockRoleHandler is a mock of RoleHandler interface
type MockRoleHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRoleHandlerMockRecorder
}

// MockRoleHandlerMockRecorder is the mock recorder for MockRoleHandler
type MockRoleHandlerMockRecorder struct {
	mock *MockRoleHandler
}

// NewMockRoleHandler creates a new mock instance
func NewMockRoleHandler(ctrl *gomock.Controller) *MockRoleHandler {
	mock := &MockRoleHandler{ctrl: ctrl}
	mock.recorder = &MockRoleHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRoleHandler) EXPECT() *MockRoleHandlerMockRecorder {
	return m.recorder
}

// Save mocks base method
func (m *MockRoleHandler) Save(w http.ResponseWriter, r *http.Request) {
	m.ctrl.Call(m, "Save", w, r)
}

// Save indicates an expected call of Save
func (mr *MockRoleHandlerMockRecorder) Save(w, r interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRoleHandler)(nil).Save), w, r)
}

// Update mocks base method
func (m *MockRoleHandler) Update(w http.ResponseWriter, r *http.Request) {
	m.ctrl.Call(m, "Update", w, r)
}

// Update indicates an expected call of Update
func (mr *MockRoleHandlerMockRecorder) Update(w, r interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleHandler)(nil).Update), w, r)
}

// Paginate mocks base method
func (m *MockRoleHandler) Paginate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.Call(m, "Paginate", w, r)
}

// Paginate indicates an expected call of Paginate
func (mr *MockRoleHandlerMockRecorder) Paginate(w, r interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockRoleHandler)(nil).Paginate), w, r)
}

// Delete mocks base method
func (m *MockRoleHandler) Delete(w http.ResponseWriter, r *http.Request) {
	m.ctrl.Call(m, "Delete", w, r)
}

// Delete indicates an expected call of Delete
func (mr *MockRoleHandlerMockRecorder) Delete(w, r interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleHandler)(nil).Delete), w, r)
}
